version: '3'

services:
  redis:
    container_name: usuprintcl-redis
    image: redis:7.0.10-alpine
    restart: always
    networks:
      - webapp
    volumes:
      - cache:/data

  server:
    build:
      context: .
    networks:
      - webapp
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    container_name: usuprintcl
    hostname: usuprintcl
    volumes:
      - .:/app

  nginx:
    build:
      context: ./nginx
    networks:
      - webapp
    ports:
      - 10623:80
    depends_on:
      - server
    restart: always
    container_name: usuprintcl-proxy
    volumes:
      - ./nginx/static:/usr/share/nginx/html

volumes:
  static:
  cache:

networks:
  webapp:
    driver: bridge
